name = "backend"
compatibility_date = "2023-12-01"

# [vars]
DATABASE_URL="postgresql://database1_owner:S2JlkK3yWdaU@ep-restless-unit-a1yyl0fh.ap-southeast-1.aws.neon.tech/database3?sslmode=require"
JWT_SECRET="secret"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"